export const data = [
    {
        image:"assets/images/property-01.jpg",
        title:"Luxury Villa",
        price:"$2.264.000",
        address:"18 Old Street Miami, OR 97219",
        bedrooms:"8",
        bathrooms:"8",
        area:"545m2",
        floor:"3",
        parking:"6 spots",
    },
    {
        image:"assets/images/property-02.jpg",
        title:"Luxury Villa",
        price:"$1.180.000",
        address:"54 New Street Florida, OR 27001",
        bedrooms:"6",
        bathrooms:"5",
        area:"450m2",
        floor:"3",
        parking:"8 spots",
    },
    {
        image:"assets/images/property-03.jpg",
        title:"Luxury Villa",
        price:"$1.460.000",
        address:"26 Mid Street Portland, OR 38540",
        bedrooms:"5",
        bathrooms:"4",
        area:"225m2",
        floor:"3",
        parking:"10 spots",
    }, {
        image:"assets/images/property-04.jpg",
        title:"Apartment",
        price:"$2.264.000",
        address:"12 Hope Street Portland, OR 12650",
        bedrooms:"4",
        bathrooms:"4",
        area:"180m2",
        floor:"38th",
        parking:"2 cars",
    }, {
        image:"assets/images/property-04.jpg",
        title:"Apartment",
        price:"$584.500",
        address:"12 Hope Street Portland, OR 12650",
        bedrooms:"4",
        bathrooms:"3",
        area:"125m2",
        floor:"25th",
        parking:"2 cars",
    },
     {
        image:"assets/images/property-05.jpg",
        title:"Penthouse",
        price:"$2.264.000",
        address:"34 Hope Street Portland, OR 42680",
        bedrooms:"4",
        bathrooms:"4",
        area:"180m2",
        floor:"38th",
        parking:"2 cars",
    },
    {
        image:"assets/images/property-06.jpg",
        title:"Modern Condo",
        price:"$450.000",
        address:"22 Hope Street Portland, OR 16540",
        bedrooms:"3",
        bathrooms:"2",
        area:"165m2",
        floor:"26th",
        parking:"3 cars",
    },
    {
        image:"assets/images/property-01.jpg",
        title:"Luxury Villa",
        price:"$2.264.000",
        address:"18 Old Street Miami, OR 97219",
        bedrooms:"8",
        bathrooms:"8",
        area:"545m2",
        floor:"3",
        parking:"6 spots",
    },
    
    {
        image:"assets/images/property-04.jpg",
        title:"Apartment",
        price:"$2.264.000",
        address:"12 Hope Street Portland, OR 12650",
        bedrooms:"4",
        bathrooms:"4",
        area:"180m2",
        floor:"38th",
        parking:"2 cars",
    },
    
]